### ISSUE TITLE
Could you provide an example in practice?

### ISSUE THREAD

**Issue by petulla** [tunnckoCore/rollup-plugin-posthtml#5]
Hi there, first I've heard of posthtml. Could you show an example of how to use this beyond the tests? Thanks.

**Comment by tunnckoCore** [comment]
hi, it is nothing more than that, that when u import file with html extension (or what u select from the include option) the variable is just a string representation of the return value of the posthtml processor. basically, it reads the given imported filepath as text and pass it directly to posthtml, which in turn returns a promise with processed text like `posthtml(stringTdxtOfTheReadFile).then(result => console.log(result))`... Where rssult is object with few properties. i believe it is result.code or result.html...  see fixtures folder for real example.

really, most rollup plugins are just very thin wrappers over other tools and which they pass string to.

hope this help and sorry im from my  huawei p10 phone

**Comment by petulla** [comment]
ok ill try to get it working, was not working for me but this is what i need.
