### ISSUE TITLE
help find your package

### ISSUE THREAD

**Issue by Scrum** [tunnckoCore/rollup-plugin-posthtml#9]
@tunnckoCore Hi, I am a posthtml package maintainer, I found your package because you have a posthtml package in dependencies. I think it will be easier for people to find your package if you add it to the list of plugins [here](https://github.com/posthtml/posthtml#plugins) and [here](https://github.com/posthtml/posthtml-plugins/), and of course the first thing to do in the posthtml organization itself - I can move your package to the posthtml organization for more popularity, for this it will be necessary to add me to this repository and then I will transfer it. The package itself will remain under your control.

let me know about any decision you make, i will understand if you are not interested

**Comment by tunnckoCore** [comment]
Of course, I'm cool with that.

I didn't maintain it recently :D And I might update it to see if it works on latest @Rollup and @posthtml.

But anyway, lets transfer it.

**Comment by tunnckoCore** [comment]
Invited you as a collaborator

https://github.com/tunnckoCore/rollup-plugin-posthtml/invitations

Let me know when we are ready so I can update the things.

**Comment by Scrum** [comment]
@tunnckoCore I am ready, but these rights are not enough to drag an organization into the post, I will need rights owners to have access to `settings`

**Comment by tunnckoCore** [comment]
Oooh, yea sorry. What about invite me in the org and I'll transfer it?

**Comment by Scrum** [comment]
Now unfortunately I can’t do this, your active participation in the project could give me a reason to do so.

**Comment by tunnckoCore** [comment]
I'll be with no permissions or in teams, just will have control on this repo. It's basically the same thing if I transfer this repo to you directly. 

Anyway, do whatever you want, I'm transferring this repo to you. :)

**Comment by Scrum** [comment]
You will have all the options in relation to your package but not in the team.

Thanks anyway.
